Repository ManageIQ/manageiq-api-client, pull requests merged in 2022-01, with the labels that each got.

#100 Allow rails 6.1
  .gitignore
  .travis.yml
  Appraisals
  Gemfile
  gemfiles/activesupport_6.0.gemfile
  gemfiles/activesupport_6.1.gemfile
  manageiq-api-client.gemspec
Labels: dependencies, rails6.1

#101 remove hakiri from readme [skip ci]
  README.md
Labels: developer

#102 Fix whitesource config files
  .whitesource
Labels: cleanup
