Repository ManageIQ/manageiq-api-client, pull requests merged in 2024-03, with the labels that each got.

#116 Update codeclimate channel to the latest in manageiq-style
  .codeclimate.yml
Labels: developer

#117 Update Changelog 0.4.1
  CHANGELOG.md
  lib/manageiq/api/client/version.rb
Labels: developer

#119 Revert drop activesupport dependency
  .github/workflows/ci.yaml
  Gemfile
  lib/manageiq/api/client.rb
  lib/manageiq/api/client/client.rb
  lib/manageiq/api/client/connection.rb
  lib/manageiq/api/client/resource.rb
  manageiq-api-client.gemspec
Labels: dependencies

#121 Raise exceptions on empty responses
  lib/manageiq/api/client/connection.rb
Labels: bug

#122 upgrade faraday from 1.0 to 2.0
  .github/workflows/ci.yaml
  lib/manageiq/api/client.rb
  lib/manageiq/api/client/connection.rb
  manageiq-api-client.gemspec
Labels: dependencies
